name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and build
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
